services:
  - type: web
    name: schulen-app
    runtime: static
    buildCommand: npm install && CI=false npm run build
    staticPublishPath: ./build
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: no-cache
    routes:
      - type: rewrite
        source: /**
        destination: /index.html 