services:
  - type: web
    name: schulen-app
    runtime: static
    buildCommand: npm install && CI=false npm run build
    staticPublishPath: ./build
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: no-cache, no-store, must-revalidate
          - key: Access-Control-Allow-Origin
            value: "*"
    routes:
      - type: rewrite
        source: /main/browseprojects
        destination: /index.html
      - type: rewrite
        source: /main/browseprojects/*
        destination: /index.html
      - type: rewrite
        source: /**
        destination: /index.html 